// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openconfig_interfaces.proto

package mt_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressesAddress struct {
	Interface            string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Family               string   `protobuf:"bytes,4,opt,name=family,proto3" json:"family,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressesAddress) Reset()         { *m = AddressesAddress{} }
func (m *AddressesAddress) String() string { return proto.CompactTextString(m) }
func (*AddressesAddress) ProtoMessage()    {}
func (*AddressesAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_347be543b845363f, []int{0}
}

func (m *AddressesAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressesAddress.Unmarshal(m, b)
}
func (m *AddressesAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressesAddress.Marshal(b, m, deterministic)
}
func (m *AddressesAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressesAddress.Merge(m, src)
}
func (m *AddressesAddress) XXX_Size() int {
	return xxx_messageInfo_AddressesAddress.Size(m)
}
func (m *AddressesAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressesAddress.DiscardUnknown(m)
}

var xxx_messageInfo_AddressesAddress proto.InternalMessageInfo

func (m *AddressesAddress) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *AddressesAddress) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *AddressesAddress) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *AddressesAddress) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressesAddress)(nil), "mt.proto.AddressesAddress")
}

func init() { proto.RegisterFile("openconfig_interfaces.proto", fileDescriptor_347be543b845363f) }

var fileDescriptor_347be543b845363f = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x2f, 0x48, 0xcd,
	0x4b, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x8f, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x4c, 0x4e,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x2d, 0x81, 0xb0, 0x94, 0x8a, 0xb8,
	0x04, 0x1c, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x53, 0x8b, 0xa1, 0x0c, 0x21, 0x19, 0x2e, 0x4e,
	0xb8, 0x0e, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x90, 0x10, 0x17, 0x4b, 0x62,
	0x4a, 0x4a, 0x91, 0x04, 0x13, 0x58, 0x02, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0x2d, 0x4e, 0xce, 0x2f,
	0x48, 0x95, 0x60, 0x06, 0x0b, 0x42, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0x69, 0x89, 0xb9, 0x99, 0x39,
	0x95, 0x12, 0x2c, 0x60, 0x61, 0x28, 0x2f, 0x89, 0x0d, 0x6c, 0xb5, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0x1a, 0xbc, 0x5b, 0xa3, 0x00, 0x00, 0x00,
}
