// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openconfig_bgp.proto

package mt_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NeighborAddress struct {
	RemoteAddr           string   `protobuf:"bytes,1,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	LocalAddr            string   `protobuf:"bytes,2,opt,name=localAddr,proto3" json:"localAddr,omitempty"`
	Asn                  string   `protobuf:"bytes,3,opt,name=asn,proto3" json:"asn,omitempty"`
	ActivateState        string   `protobuf:"bytes,4,opt,name=activateState,proto3" json:"activateState,omitempty"`
	AdminState           string   `protobuf:"bytes,5,opt,name=adminState,proto3" json:"adminState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeighborAddress) Reset()         { *m = NeighborAddress{} }
func (m *NeighborAddress) String() string { return proto.CompactTextString(m) }
func (*NeighborAddress) ProtoMessage()    {}
func (*NeighborAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bea0e87551ca59, []int{0}
}

func (m *NeighborAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborAddress.Unmarshal(m, b)
}
func (m *NeighborAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborAddress.Marshal(b, m, deterministic)
}
func (m *NeighborAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborAddress.Merge(m, src)
}
func (m *NeighborAddress) XXX_Size() int {
	return xxx_messageInfo_NeighborAddress.Size(m)
}
func (m *NeighborAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborAddress proto.InternalMessageInfo

func (m *NeighborAddress) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *NeighborAddress) GetLocalAddr() string {
	if m != nil {
		return m.LocalAddr
	}
	return ""
}

func (m *NeighborAddress) GetAsn() string {
	if m != nil {
		return m.Asn
	}
	return ""
}

func (m *NeighborAddress) GetActivateState() string {
	if m != nil {
		return m.ActivateState
	}
	return ""
}

func (m *NeighborAddress) GetAdminState() string {
	if m != nil {
		return m.AdminState
	}
	return ""
}

type NeighborAddresses struct {
	Na                   []*NeighborAddress `protobuf:"bytes,1,rep,name=na,proto3" json:"na,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NeighborAddresses) Reset()         { *m = NeighborAddresses{} }
func (m *NeighborAddresses) String() string { return proto.CompactTextString(m) }
func (*NeighborAddresses) ProtoMessage()    {}
func (*NeighborAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4bea0e87551ca59, []int{1}
}

func (m *NeighborAddresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeighborAddresses.Unmarshal(m, b)
}
func (m *NeighborAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeighborAddresses.Marshal(b, m, deterministic)
}
func (m *NeighborAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeighborAddresses.Merge(m, src)
}
func (m *NeighborAddresses) XXX_Size() int {
	return xxx_messageInfo_NeighborAddresses.Size(m)
}
func (m *NeighborAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_NeighborAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_NeighborAddresses proto.InternalMessageInfo

func (m *NeighborAddresses) GetNa() []*NeighborAddress {
	if m != nil {
		return m.Na
	}
	return nil
}

func init() {
	proto.RegisterType((*NeighborAddress)(nil), "mt.proto.NeighborAddress")
	proto.RegisterType((*NeighborAddresses)(nil), "mt.proto.NeighborAddresses")
}

func init() { proto.RegisterFile("openconfig_bgp.proto", fileDescriptor_a4bea0e87551ca59) }

var fileDescriptor_a4bea0e87551ca59 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x2f, 0x48, 0xcd,
	0x4b, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x8f, 0x4f, 0x4a, 0x2f, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0xc8, 0x2d, 0x81, 0xb0, 0x94, 0x96, 0x33, 0x72, 0xf1, 0xfb, 0xa5, 0x66, 0xa6, 0x67,
	0x24, 0xe5, 0x17, 0x39, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x0b, 0xc9, 0x71, 0x71, 0x15, 0xa5,
	0xe6, 0xe6, 0x97, 0xa4, 0x82, 0x04, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x84,
	0x64, 0xb8, 0x38, 0x73, 0xf2, 0x93, 0x13, 0x73, 0xc0, 0xd2, 0x4c, 0x60, 0x69, 0x84, 0x80, 0x90,
	0x00, 0x17, 0x73, 0x62, 0x71, 0x9e, 0x04, 0x33, 0x58, 0x1c, 0xc4, 0x14, 0x52, 0xe1, 0xe2, 0x4d,
	0x4c, 0x2e, 0xc9, 0x2c, 0x4b, 0x2c, 0x49, 0x0d, 0x2e, 0x49, 0x2c, 0x49, 0x95, 0x60, 0x01, 0xcb,
	0xa1, 0x0a, 0x82, 0x6c, 0x4d, 0x4c, 0xc9, 0xcd, 0xcc, 0x83, 0x28, 0x61, 0x85, 0xd8, 0x8a, 0x10,
	0x51, 0xb2, 0xe3, 0x12, 0x44, 0x73, 0x68, 0x6a, 0xb1, 0x90, 0x26, 0x17, 0x53, 0x5e, 0xa2, 0x04,
	0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0xa4, 0x1e, 0xcc, 0x57, 0x7a, 0x68, 0x0a, 0x83, 0x98, 0xf2,
	0x12, 0x93, 0xd8, 0xc0, 0x52, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xdf, 0xbd, 0xd0,
	0x12, 0x01, 0x00, 0x00,
}
